### PR TITLE
Added auth

### PR DESCRIPTION
**Pull request by ayush-git228**

### CODE REVIEW

**Comment by jmsv** [comment]
Backend auth stuff looks good 😀 Are you happy to add signup & login to frontend too?

**Comment by ayush-git228** [comment]
Thanks @jmsv . I'm glad that you like my work and regarding connecting frontend, right now I'm facing some issues with my laptop so will connect you tomorrow if I' am ready to do so or not.

**Comment by ayush-git228** [comment]
And I actually created another package.json in the src folder where you'll find all the dependencies needed for auth  and I not add them in the main package.json file.

**Comment by jmsv** [comment]
> And I actually created another package.json in the src folder where you'll find all the dependencies needed for auth and I not add them in the main package.json file.

Ah yeah missed that - I think it's better to keep the package index in the root directory though, and just code in the `src` directory

**Comment by ayush-git228** [comment]
> > And I actually created another package.json in the src folder where you'll find all the dependencies needed for auth and I not add them in the main package.json file.
> 
> Ah yeah missed that - I think it's better to keep the package index in the root directory though, and just code in the `src` directory

:+1:

**Pull request closed without merging**
